name: 'Checkov hard-fail'
description: 'Run checkov with the possibility to hard-fail'
inputs:
  hard-fail-on:  # id of input
    description: 'Comma seperated list of controls that are not allowed to fail or skip.'
    required: false
    default: 'CKV2_AWS_40,CKV_AWS_110'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.hard-fail-on }}
