name: 'Checkov hard-fail'
description: 'Run checkov with the possibility to hard-fail'
inputs:
  hard-fail-on:
    description: 'Comma seperated list of controls that are not allowed to fail or skip.'
    required: true
  path:
    description: 'Path with files to check. Defaults to the the root.'
    required: false
    default: '.'
  skip-checks:
    description: 'Comma seperated list of controls to skip.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.hard-fail-on }}
    - ${{ inputs.path }}
    - ${{ inputs.skip-checks }}
